#!/bin/sh

mkdir -p ~/.ssh
echo "$AWS_EC2_KEY" > ~/.ssh/aws.pem

echo $GITHUB_REF
# split by '/', get last occurence, src: https://stackoverflow.com/a/3162500/4858751
branch=${GITHUB_REF##*/}
declare -A branch_inventory
branch_inventory['master']='production'
branch_inventory['dev']='staging'
echo ${branch_inventory["$branch"]}

ls -lah
cd /github/workspace/ansible

# ansible-playbook --key-file ~/.ssh/aws.pem deploy.yaml
