export const SET_HOME_TAB_INDEX = "SET_HOME_TAB_INDEX";
export const SET_BOTTOM_NAVIGATION_INDEX = "SET_BOTTOM_NAVIGATION_INDEX";

export const SET_USER = "SET_USER";

export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
