export const SET_HOME_TAB_INDEX = "SET_HOME_TAB_INDEX";
export const SET_BOTTOM_NAVIGATION_INDEX = "SET_BOTTOM_NAVIGATION_INDEX";

export const SET_USER = "SET_USER";

export const OPEN_SNACKBAR = "OPEN_SNACKBAR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";

export const OPEN_ALERT = "OPEN_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";

export const SET_REDIRECT_AFTER_AUTH = "SET_REDIRECT_AFTER_AUTH ";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_TAB = "SET_SEARCH_TAB";

export const SET_SEED = "SET_SEED";
