name: deploy

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

jobs:
  deploy:
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install and build
        run: |
          npm install
          npm run build
        working-directory: client
        env:
          CI: false
      - name: run ansible action
        uses: ./.github/actions/ansible
        env:
          AWS_EC2_KEY: ${{ secrets.AWS_EC2_KEY }}
